'use strict';
/* Writes motion.css: the site's easing tokens, generated from the same spring physics lib/motion.js runs in the browser.
   `node scripts/build_motion.js` writes the file; `--check` fails if the committed file is out of date (CI runs this as a test). */
const fs = require('node:fs'), path = require('node:path');
const M = require('../lib/motion.js');

const OUT = path.join(__dirname, '..', 'motion.css');
const bez = ([a, b, c, d]) => `cubic-bezier(${a}, ${b}, ${c}, ${d})`;
// token name -> the spring it is made from. Only these three are used by the stylesheet.
const TOKENS = ['settle', 'soft', 'snappy'];

function css() {
  const made = TOKENS.map(name => ({ name, ...M.springEasing(M.SPRINGS[name]) }));
  const lines = [
    '/* Generated by scripts/build_motion.js from lib/motion.js. Do not edit by hand: run `npm run motion:build`.',
    '   --mo-out and --mo-in-out are the intro\'s own curves. The --mo-settle, --mo-soft and --mo-snappy easings are springs',
    '   solved in closed form and sampled into CSS linear(); their -d companions are how long each takes to come to rest. */',
    ':root {',
    `  --mo-out: ${bez(M.CURVES.out)};`,
    `  --mo-in-out: ${bez(M.CURVES.inOut)};`,
    '  /* browsers without linear() get the intro curve over the same time */',
    ...made.flatMap(t => [`  --mo-${t.name}: var(--mo-out);`, `  --mo-${t.name}-d: ${t.duration}ms;`]),
    '}',
    '@supports (transition-timing-function: linear(0, 1)) {',
    '  :root {',
    ...made.map(t => `    --mo-${t.name}: ${t.css};`),
    '  }',
    '}',
    ''
  ];
  return lines.join('\n');
}

if (require.main === module) {
  const next = css();
  if (process.argv.includes('--check')) {
    const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (have !== next) { console.error('motion.css is out of date: run `npm run motion:build`'); process.exit(1); }
    console.log('motion.css is up to date');
  } else { fs.writeFileSync(OUT, next); console.log('wrote motion.css (' + next.length + ' bytes)'); }
}
module.exports = { css, TOKENS };
